// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pvadpahhmlrodrwddjcy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB2YWRwYWhobWxyb2Ryd2RkamN5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM3NjY1MDYsImV4cCI6MjA4OTM0MjUwNn0.UCYtC1ZZzX0KPirGOaO3f4tZ6o9b9qg96aE1ALGRzFk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});